services:
  mysql:
    image: mysql:8.0
    container_name: cerveza_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cerveza_db
      MYSQL_USER: cerveza_user
      MYSQL_PASSWORD: cerveza_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
